#! /bin/bash
docker run \
        --rm \
        -v /home/tim/projects/stock_scraper:/stock-scraper \
        -w /stock-scraper \
        scrapy \
        crawl security \
        -a folder=/stock-scraper \
        -a symbol='/stock-scraper/symbols'
